version: "3.9"
services:
    db:
        image: postgres:latest
        ports:
            - 5434:5432
        env_file:
            - .dockerenv
        volumes:
            - data:/var/lib/postgresql/data

volumes:
    data:
